FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends openjdk-21-jre-headless && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir pyspark delta-spark

WORKDIR /workspace
